# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DixonColesParameterKey": "00_core.ipynb",
         "offence_key": "00_core.ipynb",
         "defence_key": "00_core.ipynb",
         "RHO_KEY": "00_core.ipynb",
         "HFA_KEY": "00_core.ipynb",
         "AVG_KEY": "00_core.ipynb",
         "OFFENCE_KEY": "00_core.ipynb",
         "DEFENCE_KEY": "00_core.ipynb",
         "UniformWeight": "00_core.ipynb",
         "ExponentialWeight": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Torvaney.github.io/mezzala/"

git_url = "https://github.com/Torvaney/mezzala/tree/master/"

def custom_doc_links(name): return None
