# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"KeyAdapter": "adapters.ipynb",
         "AttributeAdapter": "adapters.ipynb",
         "LumpedAdapter": "adapters.ipynb",
         "ModelBlockABC": "blocks.ipynb",
         "BaseRate": "blocks.ipynb",
         "HomeAdvantage": "blocks.ipynb",
         "TeamStrength": "blocks.ipynb",
         "KeyBlock": "blocks.ipynb",
         "ConstantBlock": "blocks.ipynb",
         "ScorelinePrediction": "models.ipynb",
         "Outcomes": "models.ipynb",
         "OutcomePrediction": "models.ipynb",
         "scoreline_to_outcome": "models.ipynb",
         "scorelines_to_outcomes": "models.ipynb",
         "DixonColes": "models.ipynb",
         "ParameterKey": "parameters.ipynb",
         "RHO_KEY": "parameters.ipynb",
         "HFA_KEY": "parameters.ipynb",
         "AVG_KEY": "parameters.ipynb",
         "TeamParameterKey": "parameters.ipynb",
         "OffenceParameterKey": "parameters.ipynb",
         "DefenceParameterKey": "parameters.ipynb",
         "UniformWeight": "weights.ipynb",
         "ExponentialWeight": "weights.ipynb",
         "KeyWeight": "weights.ipynb"}

modules = ["adapters.py",
           "blocks.py",
           "__init__.py",
           "models.py",
           "parameters.py",
           "weights.py"]

doc_url = "https://Torvaney.github.io/mezzala/"

git_url = "https://github.com/Torvaney/mezzala/tree/master/"

def custom_doc_links(name): return None
