# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UniformWeight": "00_core.ipynb",
         "ExponentialWeight": "00_core.ipynb",
         "DixonColesParameterKey": "00_core.ipynb",
         "RHO_KEY": "00_core.ipynb",
         "HFA_KEY": "00_core.ipynb",
         "AVG_KEY": "00_core.ipynb",
         "KeyAdapter": "00_core.ipynb",
         "AttributeAdapter": "00_core.ipynb",
         "LumpedAdapter": "00_core.ipynb",
         "DixonColes": "00_core.ipynb",
         "ModelBlockABC": "00_core.ipynb",
         "BaseRate": "00_core.ipynb",
         "HomeAdvantage": "00_core.ipynb",
         "TeamStrength": "00_core.ipynb",
         "KeyBlock": "00_core.ipynb"}

modules = ["__init__.py"]

doc_url = "https://Torvaney.github.io/mezzala/"

git_url = "https://github.com/Torvaney/mezzala/tree/master/"

def custom_doc_links(name): return None
